//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void ACMP1_enter_DefaultMode_from_RESET(void);
extern void DAC0_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void OPAMP0_enter_DefaultMode_from_RESET(void);
extern void OPAMP1_enter_DefaultMode_from_RESET(void);
extern void OPAMP2_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void LETIMER0_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define COM1_PIN            (10)
#define COM1_PORT           (gpioPortE)

#define COM2_PIN            (11)
#define COM2_PORT           (gpioPortE)

#define COM3_PIN            (12)
#define COM3_PORT           (gpioPortE)

#define COM4_PIN            (13)
#define COM4_PORT           (gpioPortE)

#define COM5_PIN            (0)
#define COM5_PORT           (gpioPortA)

#define COM6_PIN            (1)
#define COM6_PORT           (gpioPortA)

#define COM7_PIN            (2)
#define COM7_PORT           (gpioPortA)

#define COM8_PIN            (0)
#define COM8_PORT           (gpioPortC)

#define GPIO_SWO_PIN        (2)
#define GPIO_SWO_PORT       (gpioPortF)

#define LEUART0_RX_PIN      (14)
#define LEUART0_RX_PORT     (gpioPortB)

#define LEUART0_TX_PIN      (13)
#define LEUART0_TX_PORT     (gpioPortB)

#define LFXO_N_PIN          (8)
#define LFXO_N_PORT         (gpioPortB)

#define LFXO_P_PIN          (7)
#define LFXO_P_PORT         (gpioPortB)

#define RE_DANFOSS_PIN      (5)
#define RE_DANFOSS_PORT     (gpioPortD)

#define RE_TR_PIN           (15)
#define RE_TR_PORT          (gpioPortC)

#define TIMER0_CC2_PIN      (1)
#define TIMER0_CC2_PORT     (gpioPortC)

#define USART1_RX_PIN       (6)
#define USART1_RX_PORT      (gpioPortD)

#define USART1_TX_PIN       (7)
#define USART1_TX_PORT      (gpioPortD)

// [User-defined pin name abstraction]$

#endif

